### PR TITLE
Login Pages, Registration Pages, Overall Changes

### PR DESCRIPTION
**Pull request by e-dinh-6**
### Login Pages, Registration Pages, Overall Changes
The following is completed in this PR: 

- Updated login.jsx to include logo
- Linked the login and registration page together 
- Created a registration page 
- Added registration page to react router that will be reached by "url/signup"
- Registration page is finished 
- The font "Manrope" is now the default font across all components 
- Changed the favicon to be the AssignMate logo 
- Changed the title of the tab to be "AssignMate" 

### Updated Login Page
image

### Sign Up Page 
image

### New Tab Look 
image

### CODE REVIEW

**Comment by chenyizhao14** [comment]
Looks even better than what we demoed in class. The URL reflects on whether it's the login or the signup page. Super clean.

**Comment by katyhosokawa** [comment]
The UI of both of these pages looks great. You made awesome progress on the Registration page, and I like how you cleaned up the login page. I don't see any changes needed

**Comment by TayingThao** [comment]
Nice! That's great. The tab logo looks a little messed up, I think it's because of the png dimensions, I'll try to fix it.

**Comment by e-dinh-6** [comment]
Thanks for pointing that out! I'll make an issue regarding that so we don't forgot it!

**Pull request merged**
