### PR TITLE
Event Page

### PR DESCRIPTION
**Pull request by chenyizhao14**
For now its just localhost:5173/events just to see.

image
This is what the event page looks like for creating an event. Still a work in progress, not too sure how to change some things in the select tags and create new tags. 
image
image
I can't figure out how to change the tags drop-down menu so that the words are on the left.
Also struggling to move the buttons of "add tag" and "cancel" to the same line, as well as the black box to select the desired color for the tag next to the name of the wanted tag. 

Once a new event is created, it shows up on the left side bar with all the other events created. Currently, it shows the tags in () in a weird way, but I was thinking of having maybe just the color of it instead.

### CODE REVIEW

**Comment by e-dinh-6** [comment]
Good work! It looks great. The other issues seem to be a style thing so no need to spend much time on it as long as main functionality seems to be complete! Looking at your code it seems that you've begun implementing backend functionality which is amazing. 

To make the buttons in-line, you can try this 
`#wrap the buttons in a div 
<div className="button-container">
  <button type="button" onClick={handleAddTag} className="tag-btn">Add Tag</button>
  <button type="button" onClick={() => setShowNewTagModal(false)} className="tag-btn">Cancel</button>
</div>

in your css file: 

.button-container {
  display: inline-block;
}
`

**Comment by katyhosokawa** [comment]
Your add event page looks good. Nice progress! Your difficulties seem minimal, so I think we can definitely implement your code your current code for now.

**Comment by chenyizhao14** [comment]
I see, thank you Emi I changed the code to reflect it.

**Comment by TayingThao** [comment]
Good job with the event page! We can easily fix those issues, don mind 👍

**Pull request merged**
