### PR TITLE
Katy

### PR DESCRIPTION
**Pull request by katyhosokawa**
image
Updates since last merge:

- Connected my frontend to the backend so the events and tasks displayed are no longer hard-coded but reflect the cloud database. 
- Improved the UI. The events are sorted by time and date. The headers are no longer hard coded and actually reflect the current day. 
- Created a task schema, services, and GET/POST/DELETE request functions. Tasks from the database are displayed on the left and can be checked. When the removed completed button is pressed, checked tasks are deleted. There is also a box to add new tasks. Let me know if you have any suggestions in terms of the front end for the to-do-list section (specifically the input box and buttons in the bottom left corner).

### CODE REVIEW

**Comment by katyhosokawa** [comment]
Created the frontend for the Landing page
image

**Comment by e-dinh-6** [comment]
LGTM!

**Comment by e-dinh-6** [comment]
I resolved the conflict in App.jsx but I'm not sure how to fix the conflict in backend.js.

**Comment by katyhosokawa** [comment]
> I resolved the conflict in App.jsx but I'm not sure how to fix the conflict in backend.js.

No worries. The conflict was from me commenting and moving functions around while I was testing. I was able to fix both conflicts.

**Comment by chenyizhao14** [comment]
Nice job connecting everything together! It looks super smooth and great additions for the remove completed on the sidebar. I think we can probably add something where if we click on the event that is shown in list view, we can view it and edit it if necessary. I'm not too sure how to connect things together, but if we can add some parts of the event.jsx that I did with the viewing and editing, that would be cool.

**Pull request merged**
