### PR TITLE
Taying

### PR DESCRIPTION
**Pull request by TayingThao**
adding my sevenday.jsx and sevenday.css. Also added the logo.png to assets. Added the seven day view page as the path: /sevenday in App.jsx

### CODE REVIEW

**Comment by chenyizhao14** [comment]
This looks pretty good, although I think it'll be better if we have the top section colored a little differently to separate it from the rest of the calendar. The groceries task is checked and uncheckable, but the do laundry in the tasks list can't be unchecked. It's a relatively small issue I think we can figure that out pretty quickly.

Another quick thing would be to move the 1:00 a little bit lower so it matches right under the dates. Probably also start from 12:00, not 1:00pm

**Comment by meiShiratori** [comment]
I agree with everything Chenyi said, one other quick suggestion, is that it might be helpful if you added some comments to explain what's going on in the front end, other than that, it looks good.

**Comment by katyhosokawa** [comment]
Great progress on the week view Taying. In terms of the front end, this looks mostly done. I'd say some minor fixes can be made to center certain elements and adjust font sizes, but these changes can be made later.

**Comment by e-dinh-6** [comment]
Looks good to me, but next time for PR , please submit a screenshot of your frontend

**Comment by TayingThao** [comment]
Oh right, sorry about that. Here's what it currently looks like:
Screenshot 2024-05-30 at 11 09 07 PM
I need to fix the sizing and placements of certain things. Will definitely be in the next push along with the backend and welcome page.

**Pull request merged**
