### PR TITLE
Katy

### PR DESCRIPTION
**Pull request by katyhosokawa**
Added the list page's jsx and css file. I also made a few corrections in service files of incorrect find function calling. Note that the code to connect list to the backend is currently commented out, as it is not fully working at this moment.
Screenshot 2024-05-30 at 7 22 12 PM

### CODE REVIEW

**Comment by e-dinh-6** [comment]
It seems like the left blue div is rounded so its not square. You can try to remove the rounding attribute so that it's square.

**Comment by katyhosokawa** [comment]
> It seems like the left blue div is rounded so its not square. You can try to remove the rounding attribute so that it's square.

I totally missed this. Your comment also made me realize that the color of the sidebar was incorrect. I found out that my CSS specifications for the entire sidebar were being overridden. I was able to fix both of these errors.

**Comment by chenyizhao14** [comment]
Dang this looks really nice. The color change the second time around is really pretty. It's looking closer and closer to the original UI design that we had in mind. I think maybe we can make the date a little bit bigger, or have it display Month, Day, because it seems like the time is larger than the date itself.

**Comment by TayingThao** [comment]
Wow looks great! Let me know which parts of the css you're set on so that we can make the headers and sidebars uniform across all our webpages.

**Pull request merged**
